In [3]:
import pandas as pd

In [4]:
t = pd.read_csv("customer_sales_messy.csv")

In [5]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [6]:
t.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [7]:
t.isnull().sum().sum()

np.int64(10)

In [8]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         53 non-null     int64
 1   Customer_Name    52 non-null     object
 2   City             51 non-null     object
 3   Product          53 non-null     object
 4   Category         52 non-null     object
 5   Quantity         53 non-null     int64
 6   Price            51 non-null     float64
 7   Order_Date       52 non-null     object
 8   Payment_Mode     52 non-null     object
 9   Salesperson      53 non-null     object
 10  Customer_Rating  51 non-null     float64
dtypes: float64(2), int64(2), object(7)
memory usage: 4.7+ KB

In [9]:
t.describe()

          Order_ID   Quantity         Price  Customer_Rating
count    53.000000  53.000000     51.000000        51.000000
mean   1024.584906   1.471698  10737.254902         4.196078
std      14.692272   0.696247  16851.970221         0.693386
min    1001.000000   1.000000    780.000000         3.000000
25%    1012.000000   1.000000   1975.000000         4.000000
50%    1024.000000   1.000000   3250.000000         4.000000
75%    1037.000000   2.000000   8350.000000         5.000000
max    1050.000000   4.000000  57000.000000         5.000000

In [10]:
t.shape

(53, 11)

In [11]:
t.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50     True
51     True
52    False
dtype: bool

In [12]:
t.duplicated().sum()

np.int64(2)

In [13]:
t.drop_duplicates()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [14]:
t.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Category', 'Quantity',
       'Price', 'Order_Date', 'Payment_Mode', 'Salesperson',
       'Customer_Rating'],
      dtype='object')

In [15]:
t[t.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [16]:
t.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [17]:
m = t.isnull().sum()

In [18]:
m = (t.isnull().mean()*100)

In [19]:
m

Order_ID           0.000000
Customer_Name      1.886792
City               3.773585
Product            0.000000
Category           1.886792
Quantity           0.000000
Price              3.773585
Order_Date         1.886792
Payment_Mode       1.886792
Salesperson        0.000000
Customer_Rating    3.773585
dtype: float64

In [20]:
t['Customer_Name'] = t['Customer_Name'].fillna('Unknown')

In [21]:
t.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [22]:
t[t.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [23]:
t["Price"]=t["Price"].fillna(t["Price"].min())

In [24]:
t[t.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [25]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [26]:
t=t.dropna()

In [27]:
t[t.isnull().any(axis=1)]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [28]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [29]:
f = pd.read_csv("customer_sales_messy.csv")

In [30]:
f.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [31]:
fnew = f.dropna(subset=["Customer_Name"])

In [32]:
fnew.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [33]:
f.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [34]:
f[f.duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0

In [35]:
f[f["Order_ID"]==1003]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0

In [36]:
f["City"].str.upper()

0       CHENNAI
1       CHENNAI
2       CHENNAI
3     BANGALORE
4     BENGALURU
5     HYDERABAD
6     HYDERABAD
7        MUMBAI
8        MUMBAI
9          PUNE
10         PUNE
11          NaN
12      CHENNAI
13        KOCHI
14        KOCHI
15      CHENNAI
16        DELHI
17        DELHI
18    HYDERABAD
19       MUMBAI
20      CHENNAI
21    BANGALORE
22    BENGALURU
23    HYDERABAD
24         PUNE
25        DELHI
26      KOLKATA
27      KOLKATA
28        KOCHI
29      CHENNAI
30      CHENNAI
31    HYDERABAD
32       MUMBAI
33       MUMBAI
34         PUNE
35        DELHI
36      KOLKATA
37      KOLKATA
38        KOCHI
39      CHENNAI
40    BANGALORE
41    HYDERABAD
42        DELHI
43      CHENNAI
44      CHENNAI
45         PUNE
46         PUNE
47          NaN
48        KOCHI
49    BENGALURU
50      CHENNAI
51        KOCHI
52         PUNE
Name: City, dtype: object

In [37]:
f["City"]=f["City"].str.upper()

In [38]:
f

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,CHENNAI,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,BANGALORE,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,BENGALURU,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,HYDERABAD,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,MUMBAI,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,MUMBAI,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,PUNE,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,KOCHI,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,CHENNAI,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,DELHI,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,DELHI,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,HYDERABAD,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,MUMBAI,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,CHENNAI,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,BANGALORE,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,BENGALURU,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,HYDERABAD,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,PUNE,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,DELHI,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,KOLKATA,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,KOLKATA,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,KOCHI,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,CHENNAI,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,CHENNAI,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,HYDERABAD,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,MUMBAI,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,MUMBAI,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,PUNE,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,DELHI,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,KOLKATA,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,KOLKATA,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,KOCHI,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,CHENNAI,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,BANGALORE,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,HYDERABAD,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,DELHI,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,CHENNAI,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,PUNE,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,PUNE,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,KOCHI,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,BENGALURU,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [39]:
f["City"].unique()

array(['CHENNAI', ' CHENNAI', 'BANGALORE', 'BENGALURU', 'HYDERABAD',
       'MUMBAI', 'PUNE', nan, 'KOCHI', 'DELHI', 'KOLKATA'], dtype=object)

In [40]:
f["City"]=f["City"].str.strip()  #for removing space

In [41]:
f["City"].unique()

array(['CHENNAI', 'BANGALORE', 'BENGALURU', 'HYDERABAD', 'MUMBAI', 'PUNE',
       nan, 'KOCHI', 'DELHI', 'KOLKATA'], dtype=object)

In [42]:
f["Customer_Name"]=f["Customer_Name"].str.title()

In [43]:
f['Customer_Name']

0        Arun Kumar
1       Priya Sharma
2        Rahul Verma
3          Divya Raj
4          Karthik S
5                NaN
6        Vijay Kumar
7         Anjali Rao
8        Manoj Patel
9          Asha Nair
10         Rohit Das
11        Neha Singh
12        Arun Kumar
13       Pooja Menon
14          Ramesh B
15        Sanjay Rao
16      Lakshmi Devi
17        Ajay Kumar
18    Meena Krishnan
19        Varun Shah
20          Nithya S
21       Rakesh Jain
22         Keerthi M
23      Suresh Kumar
24        Pavithra R
25         Gokul Raj
26        Ishita Sen
27      Deepak Singh
28        Anu Joseph
29          Naveen P
30          Sowmya R
31        Hari Krish
32       Swathi Rao
33         Prakash N
34          Geetha S
35         Mohan Raj
36       Riya Kapoor
37        Abhishek T
38        Farah Khan
39          Naveen P
40         Divya Raj
41        Siva Kumar
42         Anita Roy
43       Rahul Verma
44      Priya Sharma
45           Kiran B
46         Rohit Das
47         Asha Nair
48            Maya S
49          Vikram J
50       Rahul Verma
51          Ramesh B
52         Rohit Das
Name: Customer_Name, dtype: object

In [44]:
f["City"].nunique()

9

In [45]:
t["Payment_Mode"]=t["Payment_Mode"].str.strip()

/tmp/ipykernel_2373/4213236604.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Payment_Mode"]=t["Payment_Mode"].str.strip()

In [46]:
t["Payment_Mode"].unique()

array(['cash', 'UPI', 'upi', 'Card', 'CARD', 'Cash', 'card'], dtype=object)

In [47]:
t["Payment_Mode"]=t["Payment_Mode"].str.title()

/tmp/ipykernel_2373/2498528561.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Payment_Mode"]=t["Payment_Mode"].str.title()

In [48]:
t["Payment_Mode"].unique()

array(['Cash', 'Upi', 'Card'], dtype=object)

In [50]:
t["Customer_Name"]= (t["Customer_Name"].str.strip().str.title())
t.head()

/tmp/ipykernel_2373/134785878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Customer_Name"]= (t["Customer_Name"].str.strip().str.title())

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [51]:
t["City"]= (t["City"].str.strip().str.title())
t.head()

/tmp/ipykernel_2373/592001893.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["City"]= (t["City"].str.strip().str.title())

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [55]:
t["City"]=t["City"].replace("Bengaluru","Bangalore")
t.head()

/tmp/ipykernel_2373/3156815800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["City"]=t["City"].replace("Bengaluru","Bangalore")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [56]:
t["Order_Date"].dtypes

dtype('O')

In [57]:
t["Order_Date"]=pd.to_datetime (t['Order_Date'],errors="coerce")
t.head()

/tmp/ipykernel_2373/1190974992.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Order_Date"]=pd.to_datetime (t['Order_Date'],errors="coerce")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [58]:
t["Order_Date"].isnull().sum()

np.int64(25)

In [59]:
t[t["Order_Date"].isnull()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,NaT,Cash,Ravi,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,NaT,Upi,Meena,5.0
10,1011,Rohit Das,Pune,Monitor,Electronics,1,11800.0,NaT,Cash,Meena,5.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,NaT,Card,Suresh,5.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,NaT,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,NaT,Upi,Meena,5.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,NaT,Card,Suresh,3.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,NaT,Cash,Meena,5.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,NaT,Upi,Suresh,3.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,NaT,Card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,NaT,Cash,Meena,4.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,NaT,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,NaT,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,NaT,Upi,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,NaT,Cash,Meena,4.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,NaT,Card,Suresh,4.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,NaT,Upi,Ravi,4.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,NaT,Cash,Meena,4.0
43,1044,Rahul Verma,Chennai,Laptop,Electronics,1,55500.0,NaT,Card,Suresh,4.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,NaT,Card,Suresh,3.0
49,1050,Vikram J,Bangalore,Office Chair,Furniture,1,6600.0,NaT,Card,Suresh,5.0
50,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0

In [61]:
t["Order_Date"]=t["Order_Date"].fillna("2026-01-01")
t.head()

/tmp/ipykernel_2373/1117246040.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Order_Date"]=t["Order_Date"].fillna("2026-01-01")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [63]:
t['Order_Date'].dt.month

0     9
1     1
2     1
3     1
4     9
5     1
6     9
7     1
8     9
9     9
10    1
12    9
13    1
14    9
15    1
17    1
18    9
19    1
20    9
22    9
23    1
24    9
25    1
26    9
27    1
29    1
30    9
31    1
32    1
33    1
35    1
36    9
37    1
38    9
39    1
40    9
41    1
42    9
43    1
44    9
46    1
48    9
49    1
50    1
51    9
52    9
Name: Order_Date, dtype: int32

In [65]:
t['Order_Date'].dt.year

0     2026
1     2026
2     2026
3     2026
4     2026
5     2026
6     2026
7     2026
8     2026
9     2026
10    2026
12    2026
13    2026
14    2026
15    2026
17    2026
18    2026
19    2026
20    2026
22    2026
23    2026
24    2026
25    2026
26    2026
27    2026
29    2026
30    2026
31    2026
32    2026
33    2026
35    2026
36    2026
37    2026
38    2026
39    2026
40    2026
41    2026
42    2026
43    2026
44    2026
46    2026
48    2026
49    2026
50    2026
51    2026
52    2026
Name: Order_Date, dtype: int32

In [66]:
t["Quantity"] = pd.to_numeric (t["Quantity"],errors="coerce")  # converts to numeric datatype

/tmp/ipykernel_2373/1290004700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Quantity"] = pd.to_numeric (t["Quantity"],errors="coerce")

In [67]:
t[t["Quantity"].isnull()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [68]:
t.dtypes

Order_ID                    int64
Customer_Name              object
City                       object
Product                    object
Category                   object
Quantity                    int64
Price                     float64
Order_Date         datetime64[ns]
Payment_Mode               object
Salesperson                object
Customer_Rating           float64
dtype: object

In [70]:
t["Total_Sales"]= (t["Price"]*t["Quantity"])
t.head()

/tmp/ipykernel_2373/246955563.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Total_Sales"]= (t["Price"]*t["Quantity"])

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Total_Sales
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,55000.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0,1700.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0,1800.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0,12500.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,13000.0

In [72]:
t[["Customer_Name","Product","Quantity","Total_Sales"]]

     Customer_Name       Product  Quantity  Total_Sales
0       Arun Kumar        Laptop         1      55000.0
1     Priya Sharma         Mouse         2       1700.0
2      Rahul Verma      Keyboard         1       1800.0
3        Divya Raj       Monitor         1      12500.0
4        Karthik S  Office Chair         2      13000.0
5          Unknown          Desk         1       8500.0
6      Vijay Kumar  Laptop Stand         2       4400.0
7       Anjali Rao        Webcam         1       3200.0
8      Manoj Patel    Headphones         1        780.0
9        Asha Nair      Keyboard         2       3500.0
10       Rohit Das       Monitor         1      11800.0
12      Arun Kumar        Laptop         1      55000.0
13     Pooja Menon          Desk         1       7800.0
14        Ramesh B         Mouse         3       2400.0
15      Sanjay Rao        Webcam         2       6200.0
17      Ajay Kumar  Laptop Stand         1       2100.0
18  Meena Krishnan        Laptop         1      56000.0
19      Varun Shah       Monitor         2      24000.0
20        Nithya S  Office Chair         1       6400.0
22       Keerthi M      Keyboard         1       1900.0
23    Suresh Kumar         Mouse         4       3280.0
24      Pavithra R        Webcam         1       3300.0
25       Gokul Raj    Headphones         2       5500.0
26      Ishita Sen  Laptop Stand         2       4600.0
27    Deepak Singh        Laptop         1      54000.0
29        Naveen P          Desk         1       8000.0
30        Sowmya R  Office Chair         2      12600.0
31      Hari Krish      Keyboard         1       1850.0
32      Swathi Rao         Mouse         2       1800.0
33       Prakash N        Webcam         1       3150.0
35       Mohan Raj  Laptop Stand         3       6150.0
36     Riya Kapoor       Monitor         1      12100.0
37      Abhishek T        Laptop         1      57000.0
38      Farah Khan          Desk         1       7900.0
39        Naveen P         Mouse         2       1560.0
40       Divya Raj      Keyboard         1       1800.0
41      Siva Kumar  Office Chair         1       6100.0
42       Anita Roy        Webcam         2       6500.0
43     Rahul Verma        Laptop         1      55500.0
44    Priya Sharma       Monitor         1      12300.0
46       Rohit Das    Headphones         2       5700.0
48          Maya S         Mouse         2       1560.0
49        Vikram J  Office Chair         1       6600.0
50     Rahul Verma      Keyboard         1       1800.0
51        Ramesh B         Mouse         3       2400.0
52       Rohit Das      Keyboard         2       3500.0

In [74]:
t.isnull().sum()

Order_ID           0
Customer_Name      0
City               0
Product            0
Category           0
Quantity           0
Price              0
Order_Date         0
Payment_Mode       0
Salesperson        0
Customer_Rating    0
Total_Sales        0
dtype: int64

In [75]:
t.duplicated().sum()

np.int64(2)

In [79]:
t=t.drop_duplicates()

In [80]:
t.duplicated().sum()

np.int64(0)

In [81]:
t['City'].value_counts()

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Name: count, dtype: int64

In [82]:
t.groupby("Product")["Total_Sales"].sum()

Product
Desk             32200.0
Headphones       11980.0
Keyboard         14350.0
Laptop          332500.0
Laptop Stand     17250.0
Monitor          72700.0
Mouse            12300.0
Office Chair     44700.0
Webcam           22350.0
Name: Total_Sales, dtype: float64

In [88]:
t.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)

Product
Laptop          332500.0
Monitor          72700.0
Office Chair     44700.0
Desk             32200.0
Webcam           22350.0
Laptop Stand     17250.0
Keyboard         14350.0
Mouse            12300.0
Headphones       11980.0
Name: Total_Sales, dtype: float64

In [83]:
new_table = pd.DataFrame(t.groupby("Product")["Total_Sales"].sum())

In [84]:
new_table.sort_values("Total_Sales",ascending = False)

              Total_Sales
Product
Laptop           332500.0
Monitor           72700.0
Office Chair      44700.0
Desk              32200.0
Webcam            22350.0
Laptop Stand      17250.0
Keyboard          14350.0
Mouse             12300.0
Headphones        11980.0

In [85]:
sales_by_category = pd.DataFrame(t.groupby("Category")["Total_Sales"].sum())

In [86]:
sales_by_category

             Total_Sales
Category
Accessories      39600.0
Electronics     443830.0
Furniture        76900.0

In [87]:
t["Payment_Mode"].value_counts()

Payment_Mode
Cash    15
Upi     15
Card    14
Name: count, dtype: int64

# Summary of City containing Orders,Total Sales,Average rating

In [89]:
t.groupby("City").agg(
    Orders = ("Order_ID","count"),
    Total_Sales = ("Total_Sales","sum"),
    Average_Rating = ("Customer_Rating","mean"),
)

           Orders  Total_Sales  Average_Rating
City
Bangalore       5      35800.0        4.000000
Chennai        11     216060.0        4.272727
Delhi           4      20250.0        4.250000
Hyderabad       6      80130.0        4.166667
Kochi           4      19660.0        4.500000
Kolkata         4     127700.0        4.500000
Mumbai          5      32930.0        3.600000
Pune            5      27800.0        4.000000

In [90]:
t.to_csv("Customer_Dataset_Cleaning.csv",index = False)